### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by jkatsnelson** [poetic/ember-cli-panels#8]
Hi,

This looks cool -- I think it might help me, but I can't tell what it is actually supposed to do yet. :)

**Comment by leonidez** [comment]
This is very much a WIP (indeed, expanding the README is one of the items). In house we're planning on using this addon along with our build tool ember-cli-cordova to provide immediate tab switching and swipe-to-navigate functionality as we see in native mobile apps. Thanks for asking and stay tuned!
